    ;PORTB nin 8 ve PORTA n?n 4 tane pinine ba?l? toplam 12 adet LED kullanarak, 
    ;0-4096 aras?nda binary tabanda ileri geri sayac? tasarlay?n?z. 
    ;PORTA n?n 4 ve 5 nolu pinlerindeki iki tane buton ile ileri mi yoksa geri mi 
    ;sayma yap?laca?? seçilecektir. 
    ;Sayma i?lemi göz ile izlenebilir yava?l?kta olacakt?r.  
    
    
    
    __CONFIG H'3F31'
    list	P=16f877a
    #include<p16f877a.inc>
    
    ORG 0X00
    
    DEGER   EQU 0X20
    ELDE    EQU 0X21
    BIR	     EQU 0X22  
    DEG1    EQU 0X23
    DEG2    EQU 0X24
 
    MOVLW 0XFF
    MOVWF DEG1
    
    MOVLW 0XFF
    MOVWF DEG2
    
    BANKSEL TRISA
    MOVLW 0x06 ; TUM PINLERI DIJITAL YAP
    MOVWF ADCON1
    MOVLW b'00110000'
    MOVWF TRISA
    MOVLW 0X00
    MOVWF TRISB
    
    RESETLE
	BANKSEL PORTA
	CLRF PORTA
	CLRF PORTB
	CLRF DEGER
	CLRF ELDE
	
	MOVLW d'1'
	MOVWF BIR

    BUTONDONGU
	BTFSC PORTA,4
	GOTO  ILERISAY
	GOTO  BUTONDONGU
	
    ILERISAY
    	BTFSC	PORTA,5
	GOTO	GERISAY
	BCF	STATUS,C
	MOVFW  BIR
	ADDWF  DEGER,F
	BTFSC  STATUS,C
	GOTO	ELDE_ARTIR
	CALL   GECIKME
	MOVFW  DEGER
	MOVWF	PORTB
	GOTO   ILERISAY
	
    ELDE_ARTIR
        BTFSC	PORTA,5
	GOTO	GERISAY
	BCF    STATUS,C
	MOVFW  BIR
	ADDWF  ELDE,F
	BTFSC  STATUS,C
	GOTO   RESETLE
	CALL   GECIKME
	MOVFW	ELDE
	MOVWF  PORTA
	GOTO   ILERISAY
	
    GERISAY
        BTFSC	PORTA,4
	GOTO	ILERISAY
	BSF	STATUS,C
	MOVFW  BIR
	SUBWF  ELDE,F
	BTFSS	STATUS,C
	GOTO	ELDE_YOK
	CALL   GECIKME
	MOVFW	ELDE
	MOVWF	PORTA
	GOTO	ELDE_VAR
	
    ELDE_YOK
        BTFSC	PORTA,4
	GOTO	ILERISAY
	BSF	STATUS,C
	MOVFW  BIR
	SUBWF  DEGER,F
	BTFSS	STATUS,C
	GOTO	RESETLE
	MOVFW	DEGER
	MOVWF	PORTB
	CALL	GECIKME
	GOTO	ELDE_YOK
    
    ELDE_VAR
        BTFSC	PORTA,4
	GOTO	ILERISAY
	BSF	STATUS,C
	MOVFW  BIR
	SUBWF  DEGER,F
	BTFSS	STATUS,C
	GOTO	GERISAY
	CALL	GECIKME
	MOVFW	DEGER
	MOVWF	PORTB
	GOTO	ELDE_VAR

    GECIKME
	DECFSZ DEG1,F
	GOTO DEG2AZALT
	MOVLW 0XFF
	MOVWF DEG1
	MOVLW 0XFF
	MOVWF DEG2
	RETURN
	
    DEG2AZALT
	DECFSZ DEG2,F
	GOTO DEG2AZALT
	GOTO GECIKME
    
    END





