;RC1 pinine bağlı olan ledin şiddetini RA0 ve RA1 pinlerini bağlı butonları kullanarak, 
;aynı şekilde RC2 pinine bağlı olan ledin ışık şiddetini ise 
;RA2 ve RA3 pinlerine bağlı butonları kullanarak arttırıp azaltan programı yazınız.
;ISIK SIDDETI YERINE DC MOTOR HIZI DA OLUR

__CONFIG H'3F31'
    
list p = 16f877a
#include<p16f877.inc>
    
DEGER2		EQU 0X26
PWM_DEGER2	EQU 0X25
PWM_DEGER	EQU 0X24
DEGER		EQU 0X21
SAYAC1	        EQU 0X22
SAYAC2		EQU 0X23 
 
ORG 0X000
    NOP 
    GOTO BASLA
    
BASLA
    BANKSEL ADCON1
    MOVLW 0X06
    MOVWF ADCON1
    
    BANKSEL TRISA
    MOVLW 0XFF
    MOVWF TRISA
    CLRF  TRISC
    
    BANKSEL CCP1CON
    MOVLW B'00001100'
    MOVWF CCP1CON
    BANKSEL CCPR1L 
    CLRF CCPR1L
    
    BANKSEL CCP2CON
    MOVLW B'00001100'
    MOVWF CCP2CON
    BANKSEL CCPR2L 
    CLRF CCPR2L
    
    BANKSEL PR2
    MOVLW D'65'
    MOVWF PR2
    
    
    BANKSEL PWM_DEGER
    MOVLW D'0'
    MOVWF PWM_DEGER
    MOVWF PWM_DEGER2
    
    BANKSEL T2CON
    MOVLW b'00000110'
    MOVWF T2CON
    CALL PWM_ISLEM
    
    KONTROL 
	BANKSEL PORTA
	BTFSC PORTA,0
	CALL PARLAKLIK1_ARTIR
	BTFSC PORTA,1
	CALL PARLAKLIK1_AZALT
	BTFSC PORTA,2
	CALL PARLAKLIK2_ARTIR
	BTFSC PORTA,3
	CALL PARLAKLIK2_AZALT
	GOTO KONTROL
	
    PARLAKLIK1_ARTIR
	BANKSEL PWM_DEGER
	MOVLW H'FF'
	SUBWF PWM_DEGER,W
	BTFSS STATUS,C
	INCF PWM_DEGER,F
	CALL PWM_ISLEM
	CALL GECIKME
	RETURN
	
    PARLAKLIK1_AZALT
	BANKSEL PWM_DEGER
	MOVF PWM_DEGER,W
	SUBLW D'0'
	BTFSS STATUS,C
	DECF PWM_DEGER,F
	CALL PWM_ISLEM
	CALL GECIKME
	RETURN
	
    PARLAKLIK2_ARTIR
	BANKSEL PWM_DEGER2
	MOVLW H'FF'
	SUBWF PWM_DEGER2,W
	BTFSS STATUS,C
	INCF PWM_DEGER2,F
	CALL PWM_ISLEM
	CALL GECIKME
	RETURN
	
    PARLAKLIK2_AZALT
	BANKSEL PWM_DEGER2
	MOVF PWM_DEGER2,W
	SUBLW D'0'
	BTFSS STATUS,C
	DECF PWM_DEGER2,F
	CALL PWM_ISLEM
	CALL GECIKME
	RETURN
	
    GECIKME 
	MOVLW D'50'
	MOVWF SAYAC1 
    GECIKME1
	MOVLW D'50'
	MOVWF SAYAC2
    GECIKME2
	DECFSZ SAYAC2,F
	GOTO GECIKME2
	DECFSZ SAYAC1,F
	GOTO GECIKME1
	RETURN
	
    PWM_ISLEM
	BANKSEL PWM_DEGER
	MOVF PWM_DEGER,W
	BANKSEL DEGER
	ANDLW B'00000011'
	MOVWF DEGER 
	SWAPF DEGER,W
	ANDLW B'11110000'
	IORLW B'00001100'
	BANKSEL CCP1CON
	MOVWF CCP1CON
	BANKSEL PWM_DEGER
	MOVF PWM_DEGER,W
	MOVWF DEGER
	RRF DEGER,F
	RRF DEGER,W
	ANDLW B'00111111'
	MOVWF CCPR1L
	
	BANKSEL PWM_DEGER2
	MOVF PWM_DEGER2,W
	BANKSEL DEGER2
	ANDLW B'00000011'
	MOVWF DEGER2
	SWAPF DEGER,W
	ANDLW B'11110000'
	IORLW B'00001100'
	BANKSEL CCP2CON
	MOVWF CCP2CON
	BANKSEL PWM_DEGER2
	MOVF PWM_DEGER2,W
	MOVWF DEGER2
	RRF DEGER2,F
	RRF DEGER2,W
	ANDLW B'00111111'
	MOVWF CCPR2L
	RETURN
	
	END
